# Generated by Django 2.0.2 on 2018-02-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('click', 'CLICK'), ('type', 'TYPE')], default='click', max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('next_action', models.ManyToManyField(related_name='_action_next_action_+', to='TestYourTech.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('id', 'ID'), ('css_selector', 'CSS_SELECTOR'), ('xpath', 'XPATH')], max_length=256)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='selector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestYourTech.Selector'),
        ),
        migrations.AddField(
            model_name='action',
            name='results',
            field=models.ManyToManyField(to='TestYourTech.Result'),
        ),
        migrations.AddField(
            model_name='action',
            name='selector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestYourTech.Selector'),
        ),
        migrations.AddField(
            model_name='action',
            name='testcases',
            field=models.ManyToManyField(to='TestYourTech.TestCase'),
        ),
    ]
