# Generated by Django 2.0.2 on 2018-02-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestYourTech', '0002_auto_20180203_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selector',
            old_name='type',
            new_name='selector_type',
        ),
        migrations.RemoveField(
            model_name='action',
            name='type',
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('click', 'CLICK'), ('type', 'TYPE'), ('url', 'GO TO URL')], default='click', max_length=256),
        ),
        migrations.AlterField(
            model_name='action',
            name='next_action',
            field=models.ManyToManyField(blank=True, related_name='_action_next_action_+', to='TestYourTech.Action'),
        ),
        migrations.AlterField(
            model_name='action',
            name='results',
            field=models.ManyToManyField(blank=True, to='TestYourTech.Result'),
        ),
        migrations.AlterField(
            model_name='action',
            name='testcases',
            field=models.ManyToManyField(blank=True, to='TestYourTech.TestCase'),
        ),
    ]
