# Generated by Django 2.0.2 on 2018-02-04 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestYourTech', '0004_auto_20180204_0141'),
        ('TestYourTech', '0004_auto_20180203_2041'),
    ]

    operations = [
    ]
