# Generated by Django 2.0.2 on 2018-02-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestYourTech', '0005_merge_20180204_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='value',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='selector',
            field=models.CharField(max_length=256),
        ),
    ]
