# Generated by Django 2.0.2 on 2018-02-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestYourTech', '0006_auto_20180204_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='left_pos',
            field=models.CharField(default='0px', max_length=256),
        ),
        migrations.AddField(
            model_name='action',
            name='top_pos',
            field=models.CharField(default='0px', max_length=256),
        ),
    ]
