# Generated by Django 2.0.2 on 2018-02-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestYourTech', '0006_auto_20180203_2340'),
        ('TestYourTech', '0007_auto_20180204_0552'),
    ]

    operations = [
    ]
