# Generated by Django 2.0.2 on 2018-02-04 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestYourTech', '0008_merge_20180204_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='left_pos',
        ),
        migrations.RemoveField(
            model_name='action',
            name='next_action',
        ),
        migrations.RemoveField(
            model_name='action',
            name='top_pos',
        ),
        migrations.AddField(
            model_name='action',
            name='prev_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestYourTech.Action'),
        ),
        migrations.AlterField(
            model_name='action',
            name='value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
