# Generated by Django 2.0.2 on 2018-02-04 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestYourTech', '0008_merge_20180204_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='next_action',
        ),
        migrations.AddField(
            model_name='action',
            name='next_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TestYourTech.Action'),
        ),
    ]
