# Generated by Django 2.0.2 on 2018-02-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestYourTech', '0008_merge_20180204_0608'),
        ('TestYourTech', '0009_auto_20180204_0134'),
    ]

    operations = [
    ]
