# Generated by Django 2.0.2 on 2018-02-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestYourTech', '0009_auto_20180204_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='prev_action',
        ),
        migrations.AddField(
            model_name='actionlink',
            name='after',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestYourTech.Action'),
        ),
        migrations.AddField(
            model_name='actionlink',
            name='this',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='TestYourTech.Action'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_link',
            field=models.ManyToManyField(through='TestYourTech.ActionLink', to='TestYourTech.Action'),
        ),
    ]
