# Generated by Django 2.0.2 on 2018-02-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestYourTech', '0012_result_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='selector',
            field=models.CharField(max_length=256),
        ),
    ]
