# Generated by Django 2.0.2 on 2018-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestYourTech', '0013_auto_20180204_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='testcases',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(blank=True, choices=[('click', 'CLICK'), ('type', 'TYPE'), ('url', 'GO TO URL'), ('submit', 'SUBMIT')], default='click', max_length=256),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='action',
            name='selector',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
