# Generated by Django 2.0.2 on 2018-02-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemVariable',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
    ]
